{{- if (include "bugsink.envSecret.create" .) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "bugsink.envSecret.name" . }}
  labels:
    {{ include "bugsink.labels" . | nindent 4 }}
stringData:
  {{/* Secret Key */}}
  {{- with (include "bugsink.secretKey" .) }}
  SECRET_KEY: {{ . | quote }}
  {{- end }}
  {{/* SMTP */}}
  {{- if and .Values.smtp.enabled (not .Values.smtp.existingSecret) }}
  EMAIL_HOST_USER: {{ .Values.smtp.username | quote }}
  EMAIL_HOST_PASSWORD: {{ .Values.smtp.password | quote }}
  {{- end }}
  {{- if not .Values.admin.existingSecret }}
  CREATE_SUPERUSER: {{ include "bugsink.admin.auth" . | quote }}
  {{- end }}
  {{- if .Values.postgresql.enabled }}
  DATABASE_URL: {{ include "bugsink.postgresql.url" . | quote }}
  {{- end }}
{{- end }}
---
{{- if (include "bugsink.extraEnvSecret.create" .) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "bugsink.extraEnvSecret.name" . }}
  labels:
    {{ include "bugsink.labels" . | nindent 4 }}
stringData:
  {{- range $secretKey, $secretValue := .Values.extraEnv.secrets }}
  {{ $secretKey }}: {{ $secretValue | quote }}
  {{- end }}
{{- end }}
